export const FETCH_PROPERTY_LIST_SUCCESS = "FETCH_CITY_CUSTOMERS_SUCCESS";
export const FETCH_PROPERTY_LIST_ERROR = "FETCH_PROPERTY_LIST_ERROR";
export const FETCH_MOST_VISITED_SUCCESS = "FETCH_MOST_VISITED_SUCCESS";
export const FETCH_MOST_VISITED_ERROR = "FETCH_MOST_VISITED_ERROR";
export const FETCH_RECENT_VISITED_SUCCESS = "FETCH_RECENT_VISITED_SUCCESS";
export const FETCH_RECENT_VISITED_ERROR = "FETCH_RECENT_VISITED_ERROR";
export const SET_BACKDROP_OPEN = "SET_BACKDROP_OPEN";
export const SET_BACKDROP_CLOSED = "SET_BACKDROP_CLOSED";
